# Bridge Parameter File
# These topics communicate from rviz (ROS2) to gazebo
# ---------------------------------------------------
#Clock
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS


